template: hello %s
defaultName: lol


database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/dbb?autoReconnect=true&useSSL=false
  user: aman
  password: Lol@123456789@
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true

defaultHystrixConfig:
  hystrix.command.DeviceServiceDependency.execution.isolation.thread.timeoutInMilliseconds: 20000000000
  hystrix.threadpool.PinCheckService.maxQueueSize: 50
  hystrix.threadpool.PinCheckService.coreSize: 5

